# Generated by Django 4.2.6 on 2023-12-20 18:31

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Precipitation',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.UUID('5f2d7ea6-2077-471a-90bd-8cf3ad517e33'), editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('precipitation', models.FloatField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.UUID('5f2d7ea6-2077-471a-90bd-8cf3ad517e33'), editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('temperature', models.FloatField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
