# Generated by Django 4.2.6 on 2023-12-20 18:40

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dewsDC', '0002_alter_precipitation_id_alter_temperature_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMoisture',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('soil_moisture', models.FloatField(db_index=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
